### ISSUE TITLE
Bad Arguments to length of list

### ISSUE THREAD

**Issue by crgdiver** [ak-rex/Requested-for-Ombi#2]
About two versions ago I started getting an error anytime I search for a movie or show.

Bad arguments to length of list
The operation length of list cannot accept the arguments: ,[<!DOCTYPE]

I can still view suggested movies but cant search to add anything. I'm using a samsung s8 plus android version 8.0.0

**Comment by crgdiver** [comment]
I'm using ombi version 3.0.3368 on ubuntu 16.04 and just discovered whenever I try to search using the Requested app it crashes ombi

**Comment by ak-rex** [comment]
I discovered the same problem last night. the login token expires after a week. I thought I had it set up to prompt you to log back in after a week but something isn't working right. going to work on fixing it tonight. you can logout then log back in and you should be good.

**Comment by crgdiver** [comment]
Wow thanks for the crazy fast reply haha you're the man! However that doesnt seem to be working for me. I even uninstalled and reinstalled and I still get the error.

**Comment by crgdiver** [comment]
Ok crazy this time I just logged out and back in again and it work! Thanks!

**Comment by ak-rex** [comment]
cool glad it's working now. I'll have a fix for that issue out soon.

**Comment by ak-rex** [comment]
fixed in version 1.5

**Comment by tidusjar** [comment]
Out of curiosity. What did you do to fix this?

**Comment by ak-rex** [comment]
when the token expired the app received a error instead of the json. I thought I had it set up to clear the token and ask to log back in but I had it set to only ask to relogin on the expire date so you received the error. I have it set up now to save the expire date, then when the app starts it checks the current date with the expiration date. if current date is on or after expiration date prompt to login to receive a new token.

**Comment by tidusjar** [comment]
OK excellent, I was worried for a second that you were storing credentials for the user then.

**Comment by ak-rex** [comment]
no worries, good looking out though.
